### ISSUE TITLE
Error while processing template: Template<template

### ISSUE THREAD

**Issue by snowy1988** [Barma-lej/landroid-card#249]
I have some Errors in the log of HA.

![image](https://github.com/Barma-lej/landroid-card/assets/143085242/484339fc-73d8-4d4b-ad01-b68cbe7ee8cc)

The landroid is currently off.

`ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ as_timedelta((value | float(0) * 60) | string) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 567, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2305, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1984, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'value' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 693, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'value' is undefined`

**Comment by snowy1988** [comment]
Just for your information.
I updated to the current beta Version with Landroid Cloud v.4.0 and the Error is gone.

**Comment by Barma-lej** [comment]
Current version of landroid_card doesn't support landroid cloud > 4, wait update
#218 
#222

**Comment by Barma-lej** [comment]
There is a new beta version [1.0.0b2](https://github.com/Barma-lej/landroid-card/releases/tag/1.0.0b2) here
